[pkgdown] attempt to fix website build
I get this warning:

-- Initialising site -----------------------------------------------------------
Copying '../../_temp/Library/pkgdown/BS5/assets/link.svg' to 'link.svg'
Copying '../../_temp/Library/pkgdown/BS5/assets/pkgdown.js' to 'pkgdown.js'
-- Building home ---------------------------------------------------------------
Error in read_xml.raw(charToRaw(enc2utf8(x)), "UTF-8", ..., as_html = as_html,  :
  Name doi:10.1126 is not XML Namespace compliant [202]
Calls: <Anonymous> ... render_page_html -> <Anonymous> -> read_html.default
Execution halted
Error: Process completed with exit code 1.

seems to be related to https://github.com/r-lib/pkgdown/issues/499
which was fixed already in 2018: https://github.com/r-lib/pkgdown/pull/509